# This patch removes the NetworkPolicy with the given name
$patch: delete
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: hello-world
---
# This patch removes the Ingress with the given name
$patch: delete
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world